### ISSUE TITLE
Diagrama y modelado de base de datos

### ISSUE THREAD

**Issue by jordiugarte** [TurboTeam-IngSoftware/TurboTeam-IngSoftware#23]
Modelar la base de datos de prueba que se va a usar para el proyecto.

**Comment by 0WLB34R** [comment]
Modelar la base de datos de prueba que se va a usar para el proyecto.

**Comment by 0WLB34R** [comment]
Se mueve al segundo sprint, está tarea está cerrada en éste sprint.
