### ISSUE TITLE
Crear Logo

### ISSUE THREAD

**Issue by 0WLB34R** [TurboTeam-IngSoftware/TurboTeam-IngSoftware#25]
Crear un simple logo para la estética del proyecto.

**Comment by jordiugarte** [comment]
![linkedin_profile_image](https://user-images.githubusercontent.com/48989035/98941497-12f1ef00-24c3-11eb-8604-f8a227ea134d.png)
![logo](https://user-images.githubusercontent.com/48989035/98941499-138a8580-24c3-11eb-8062-ab77ac43c2e0.png)
![logo_transparent](https://user-images.githubusercontent.com/48989035/98941501-14231c00-24c3-11eb-981c-95a063787e20.png)
![pinterest_board_photo](https://user-images.githubusercontent.com/48989035/98941504-14231c00-24c3-11eb-93fa-f682ef133822.png)
![pinterest_profile_image](https://user-images.githubusercontent.com/48989035/98941506-14bbb280-24c3-11eb-80e3-6fe0abcfc3ca.png)
![twitter_header_photo_1](https://user-images.githubusercontent.com/48989035/98941508-15544900-24c3-11eb-9901-b72f291346c9.png)
![twitter_header_photo_2](https://user-images.githubusercontent.com/48989035/98941510-15544900-24c3-11eb-81a9-9b4f668ba688.png)
![twitter_profile_image](https://user-images.githubusercontent.com/48989035/98941511-15ecdf80-24c3-11eb-9869-c479b35b7285.png)
![youtube_profile_image](https://user-images.githubusercontent.com/48989035/98941512-15ecdf80-24c3-11eb-8a40-4bdccea3d0c4.png)
![facebook_cover_photo_1](https://user-images.githubusercontent.com/48989035/98941514-15ecdf80-24c3-11eb-8ce4-e996372d7cdb.png)
![facebook_cover_photo_2](https://user-images.githubusercontent.com/48989035/98941515-16857600-24c3-11eb-8df8-0a6d1437a1dc.png)
![facebook_profile_image](https://user-images.githubusercontent.com/48989035/98941516-16857600-24c3-11eb-83a6-c9296ac7d3fc.png)
![favicon](https://user-images.githubusercontent.com/48989035/98941517-171e0c80-24c3-11eb-88d5-8cf4b86b3600.png)
![instagram_profile_image](https://user-images.githubusercontent.com/48989035/98941519-171e0c80-24c3-11eb-8eeb-98e69b9de189.png)
![linkedin_banner_image_1](https://user-images.githubusercontent.com/48989035/98941520-17b6a300-24c3-11eb-8e1f-a9a4b1f100c3.png)
![linkedin_banner_image_2](https://user-images.githubusercontent.com/48989035/98941524-17b6a300-24c3-11eb-90de-d751db5f1bd8.png)

**Comment by 0WLB34R** [comment]
Logo creado.

Esta tarea se puede cerrar.
