### ISSUE TITLE
Página de Login (Front-End)

### ISSUE THREAD

**Issue by 0WLB34R** [TurboTeam-IngSoftware/TurboTeam-IngSoftware#38]
Se necesita construir la página de Login para que sea visualmente satisfactoria según los requerimientos y mockups del sistema.

**Comment by 0WLB34R** [comment]
Front-end casi finalizado. Se necesita revisar e implementar conexión con back-end.

**Comment by PatBruckner** [comment]
Página de login funcional y terminada
